// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kjdjDy9CSdNSuNjp0a5iQjg1sqnO-AI',
    appId: '1:643993989639:web:247875d3d35583f56df0a2',
    messagingSenderId: '643993989639',
    projectId: 'fir-cd391',
    authDomain: 'fir-cd391.firebaseapp.com',
    storageBucket: 'fir-cd391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPakKZiqg6FeZY03i8tk70fpG2MK1oEV0',
    appId: '1:643993989639:android:e737cc26692e41336df0a2',
    messagingSenderId: '643993989639',
    projectId: 'fir-cd391',
    storageBucket: 'fir-cd391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pn8enWyUbf9bzkNxy3RVRndKa_CYmIc',
    appId: '1:643993989639:ios:5ecd71fba4b26d4d6df0a2',
    messagingSenderId: '643993989639',
    projectId: 'fir-cd391',
    storageBucket: 'fir-cd391.appspot.com',
    iosBundleId: 'com.shahid.newsglobe',
  );
}
